// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8zexk0uU8AeW4HYDFZK7NaXS2wtqKpkw',
    appId: '1:701224176115:web:bc7d6103d8f57313972a86',
    messagingSenderId: '701224176115',
    projectId: 'xrcapstone22wi-team8',
    authDomain: 'xrcapstone22wi-team8.firebaseapp.com',
    storageBucket: 'xrcapstone22wi-team8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeGacK7gqIt6ijFVwoYO3pImqiZS9a2og',
    appId: '1:701224176115:android:e622760d13df67dd972a86',
    messagingSenderId: '701224176115',
    projectId: 'xrcapstone22wi-team8',
    storageBucket: 'xrcapstone22wi-team8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0efhefY3AJs3poNc8XNlBF7N7A4-i0xM',
    appId: '1:701224176115:ios:9f71fdd233c7e174972a86',
    messagingSenderId: '701224176115',
    projectId: 'xrcapstone22wi-team8',
    storageBucket: 'xrcapstone22wi-team8.appspot.com',
    iosClientId: '701224176115-q0olq4q0sjg604hok9nome5cum9dk6ns.apps.googleusercontent.com',
    iosBundleId: 'edu.washington.cs.realitylab.xrcapstone22wi-team8.iOS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0efhefY3AJs3poNc8XNlBF7N7A4-i0xM',
    appId: '1:701224176115:ios:49cb80ef054c856b972a86',
    messagingSenderId: '701224176115',
    projectId: 'xrcapstone22wi-team8',
    storageBucket: 'xrcapstone22wi-team8.appspot.com',
    iosClientId: '701224176115-lf9rdvrdmsjim7j71t4olmq7hc9f1qc8.apps.googleusercontent.com',
    iosBundleId: 'edu.washington.cs.realitylab.xrcapstone22wi-team8.macOS',
  );
}
